# Generated by Django 4.2.30 on 2026-04-28 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_remove_project_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pj_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pj_reviewing_projects', to=settings.AUTH_USER_MODEL, verbose_name='PJレビュー者'),
        ),
        migrations.CreateModel(
            name='WorkingHourSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily_hours', models.DecimalField(decimal_places=1, default=8.0, max_digits=4, verbose_name='1日あたりの稼働時間')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_hour_setting', to='projects.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': '稼働時間設定',
                'verbose_name_plural': '稼働時間設定一覧',
            },
        ),
        migrations.CreateModel(
            name='UserPto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='有休日')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ptos', to='projects.project', verbose_name='プロジェクト')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptos', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '有休日',
                'verbose_name_plural': '有休日一覧',
                'ordering': ['date'],
                'unique_together': {('project', 'user', 'date')},
            },
        ),
    ]
