# Generated by Django 4.2.30 on 2026-04-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_pj_reviewer_workinghoursetting_userpto'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghoursetting',
            name='pjrv_buffer_days',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='PJRVバッファ営業日数'),
        ),
    ]
