# Generated by Django 4.2.30 on 2026-04-29 07:17

import apps.accounts.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='holiday_weekdays',
            field=models.JSONField(default=apps.accounts.models._default_holiday_weekdays, verbose_name='休みの曜日'),
        ),
        migrations.CreateModel(
            name='TenantHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日付')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='名称')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='accounts.tenant', verbose_name='テナント')),
            ],
            options={
                'verbose_name': 'テナント休日',
                'verbose_name_plural': 'テナント休日一覧',
                'ordering': ['date'],
                'unique_together': {('tenant', 'date')},
            },
        ),
    ]
