# Generated by Django 4.2.30 on 2026-04-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tenant_holiday_weekdays_tenantholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='productivity_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='工数倍率'),
        ),
    ]
