# Generated by Django 4.2.30 on 2026-04-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_project_3a8250_idx',
            old_name='tasks_task_project_parent_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_quarter_0b5920_idx',
            old_name='tasks_task_quarter_idx',
        ),
    ]
