# Generated by Django 4.2.30 on 2026-04-28 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_rename_tasks_task_project_parent_deleted_idx_tasks_task_project_3a8250_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'タスク', 'verbose_name_plural': 'タスク一覧'},
        ),
        migrations.AddField(
            model_name='task',
            name='dates_manual',
            field=models.BooleanField(default=False, verbose_name='日付手動入力フラグ'),
        ),
        migrations.AddField(
            model_name='task',
            name='tm_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tm_reviewing_items', to=settings.AUTH_USER_MODEL, verbose_name='TMレビュー者'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_kind',
            field=models.CharField(blank=True, choices=[('実装', '実装'), ('TMRV', 'TMRV'), ('PJRV', 'PJRV'), ('レビュー修正', 'レビュー修正')], max_length=20, null=True, verbose_name='タスク分類'),
        ),
    ]
